# name: SonarCloud Analysis

# on:
#   push:
#     branches:
#       - release-3.7

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up JDK 21
#         uses: actions/setup-java@v3
#         with:
#           distribution: 'temurin'
#           java-version: '21'

#       - name: Cache SonarCloud packages
#         uses: actions/cache@v3
#         with:
#           path: ~/.sonar/cache
#           key: ${{ runner.os }}-sonar
#           restore-keys: ${{ runner.os }}-sonar


#       - name: SonarCloud Scan
#         env:
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#         run: mvn verify sonar:sonar -Dsonar.projectKey=Maheenrz_eclipse-ditto -Dsonar.organization=maheenrz -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}



name: SonarCloud Analysis

on:
  push:
    branches:
      - release-3.7
  workflow_dispatch:

jobs:
  build:
    name: Build and Analyze (SonarCloud)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and analyze with SonarCloud (skip tests)
        run: mvn clean install -Dmaven.test.skip=true sonar:sonar -Dsonar.branch.name=release-3.7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
