name: SonarCloud Analysis
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to analyze'
        required: true
        default: 'release-3.7'

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.release_tag }}  # Remove repository line since we're using current repo
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temulin'
    
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
    
    - name: Run SonarCloud
      run: ./gradlew sonar -Dsonar.projectVersion=${{ github.event.inputs.release_tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}